# MySQL designed for container-native deployment on Joyent's Triton platform.

mysql:
    image: autopilotpattern/mysql:latest
    mem_limit: 4g
    restart: always
    env_file: _env
    environment:
      - CONTAINERBUDDY=file:///etc/containerbuddy.json
      - MANTA_PRIVATE_KEY

    # expose for linking, but each container gets a private IP for
    # internal use as well
    expose:
      - 3306

# ---------------------------------------------------
# Consul as a service discovery tier

consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1
